### ISSUE TITLE
No alert for a successful copy to clipboard

### ISSUE THREAD

**Issue by jagnani73** [erkangcmn/Software-Library-With-React#10]
There should be an alert to notify the user that the content has been copied successfully for better User Experience

**Comment by jagnani73** [comment]
@erkangcmn I would like to work on this issue!

**Comment by erkangcmn** [comment]
> @erkangcmn Bu konu üzerinde çalışmak istiyorum!
Of course, you can work

**Comment by jagnani73** [comment]
@erkangcmn could you please assign me this issue?

**Comment by Atharv777** [comment]
please add hacktoberfest 2021 label, I have made a PR #11 please merge it

**Comment by jagnani73** [comment]
@Atharv777, I would suggest you add `fixes #10` in your PR description
It would help auto-close the issue as soon as the PR is merged 😄

**Comment by Atharv777** [comment]
hey @jagnani73 I have added `fixes #10` in my PR description. Please merge my PR

**Comment by Atharv777** [comment]
@jagnani73 Please add **hacktoberfest 2021** and **hacktoberfest-accepted** label
